global: 
    root_dir: ""
    iteration: "library_aditi_balanced_run2"
    enable_preprocessing: true
transformer:
    fps: 5
    path: "data/library"
    data_save_file: "data/processed/library" #file path without .npz
data:
    HEIGHT: 128
    WIDTH: 128
    CHANNELS: 3
    SEQUENCE_LENGTH: 8
trainer:
    patch_size: 4
    img_channel: 1
    img_width: 128
    filter_size: 5
    stride: 1
    layer_norm: 0
    visual: 0
    BATCH: 8
    lr: 0.01
    epochs: 20
    lambda: 0.001  #L2 regularization #changed from 1e-4
    num_classes: 3
    model_save_path: "models/"
    model:
        name: "ConvLSTM"
        convlstm_hidden: 128
        num_conv_lstm_layers: 1
        pretrained_path: ""
        optimizer_path: ""
