global: 
    root_dir: ""
    iteration: "debug"
    enable_preprocessing: false
transformer:
    fps: 5
    path: "data/ghc_data"
    data_save_file: "data/processed/ghc_data" #file path without .npz
data:
    HEIGHT: 128
    WIDTH: 128
    CHANNELS: 3
    SEQUENCE_LENGTH: 8
trainer:
    BATCH: 8
    lr: 0.01
    epochs: 20
    lambda: 0.001  #L2 regularization #changed from 1e-4
    num_classes: 3
    enable_qat: True
    model_save_path: "models/"
    model:
        name: "ConvLSTM"
        convlstm_hidden: 256
        num_conv_lstm_layers: 1
        pretrained_path: ""
        optimizer_path: ""
