global: 
    root_dir: ""
    iteration: "debug"
    enable_preprocessing: false
transformer:
    fps: 5
    path: "data/tiny_data"
    data_save_file: "data/processed/tiny_data" #file path without .npz
    enable_benchmark_test: true
    test_path: "data/test/Indoor"
    test_save_file: "data/processed/test/Indoor" #file path without .npz
data:
    HEIGHT: 64
    WIDTH: 64
    CHANNELS: 3
    SEQUENCE_LENGTH: 20
trainer:
    BATCH: 8
    lr: 0.01
    epochs: 20
    lambda: 0.001  #L2 regularization #changed from 1e-4
    num_classes: 3
    model_save_path: "models/"
    model:
        name: "ConvLSTM"
        convlstm_hidden: 256
        num_conv_lstm_layers: 1
        pretrained_path: ""
        optimizer_path: ""
