global:
    root_dir: ""
    iteration: "debug"
    enable_preprocessing: false
    seed: 8
    enable_intent: false
transformer:
    fps: 2
    path: "data/Indoor - Seattle Library"
    data_save_file: "data/processed/Indoor - Seattle Library" #file path without .npz
    enable_benchmark_test: true
    test_path: "data/test/Mixed"
    test_save_file: "data/processed/test/Mixed" #file path without .npz
data:
    HEIGHT: 64
    WIDTH: 64
    CHANNELS: 1
    SEQUENCE_LENGTH: 10
    VAL_INTENT: ""
trainer:
    patch_size: 4
    img_channel: 1
    img_width: 128
    filter_size: 5
    stride: 1
    layer_norm: 0
    visual: 0
    BATCH: 8
    lr: 0.01
    epochs: 2
    lambda: 0.001  #L2 regularization #changed from 1e-4
    num_classes: 3
    model_save_path: "models/"
    model:
        name: "ConvLSTM"
        convlstm_hidden: "256"
        num_conv_lstm_layers: 1
        pretrained_path: ""
        optimizer_path: ""
