global: 
    root_dir: ""
    iteration: "seattle_library_intent_weighted_loss_2_layers"
    enable_preprocessing: false
    seed: 8
transformer:
    fps: 4
    path: "data/library"
    data_save_file: "data/processed/seattle_library_4fps" #file path without .npz
data:
    HEIGHT: 64
    WIDTH: 64
    CHANNELS: 3
    SEQUENCE_LENGTH: 20
trainer:
    BATCH: 4
    lr: 0.01
    epochs: 20
    lambda: 0.001  #L2 regularization #changed from 1e-4
    num_classes: 3
    model_save_path: "models/"
    model:
        name: "ConvLSTM"
        convlstm_hidden: "512"
        num_conv_lstm_layers: 1
        pretrained_path: ""
        optimizer_path: ""
