global: 
    root_dir: ""
    iteration: "quantization"
    enable_preprocessing: true
transformer:
    fps: 5
    path: "data/library"
    data_save_file: "data/processed/library" #file path without .npz
data:
    HEIGHT: 128
    WIDTH: 128
    CHANNELS: 3
    SEQUENCE_LENGTH: 8
trainer:
    BATCH: 8
    lr: 0.01
    epochs: 20
    lambda: 0.001  #L2 regularization #changed from 1e-4
    num_classes: 3
    enable_qat: False
    model_save_path: "models/"
    model:
        name: "ConvLSTM"
        convlstm_hidden: 128
        num_conv_lstm_layers: 1
        pretrained_path: ""
        optimizer_path: ""
