global: 
    root_dir: ""
    iteration: "debug"
    enable_preprocessing: true
transformer:
    fps: 5
    path: "data/tiny_data"
    data_save_file: "data/processed/tiny_data" #file path without .npz
data:
    HEIGHT: 224 #128
    WIDTH: 224 #128
    CHANNELS: 3
    SEQUENCE_LENGTH: 8
trainer:
    BATCH: 8
    lr: 0.01
    epochs: 20
    lambda: 0.001  #L2 regularization #changed from 1e-4
    num_classes: 3
    model_save_path: "models/"
    #model:
    #    name: "ConvLSTM"
    #    convlstm_hidden: 256
    #    num_conv_lstm_layers: 1
    #    pretrained_path: ""
    #    optimizer_path: ""
    model:
         name: "LSTM_Multimodal"
         lstm_hidden: 128 #try 128 later
         num_lstm_layers: 2 #try 3,4,5 later
         dense_frame_input_dim: 1000 #final input is dense_frame_input_dim + sensor_data_dim
         train_with_sensor: True
         sensor_attr_list:
             - "Gyrometer:Gyrometer - X axis"
             - "Gyrometer:Gyrometer - Y axis"
             - "Gyrometer:Gyrometer - Z axis"
             - "Magnetometer:Magnetometer - X axis"
             - "Magnetometer:Magnetometer - Y axis"
             - "Magnetometer:Magnetometer - Z axis"
             - "Magnetometer:Magnetometer - X axis"
             - "Magnetometer:Magnetometer - Y axis"
             - "Magnetometer:Magnetometer - Z axis"
             - "Accelerometer:Acceleration - X axis"
             - "Accelerometer:Acceleration - Y axis"
             - "Accelerometer:Acceleration - Z axis"
         pretrained_path: ""
         optimizer_path: ""
