global:
    root_dir: ""
    iteration: "intent_Predrnn_focal_dropout"
    enable_preprocessing: false
    seed: 8
    enable_intent: true
    enable_wandb: true
transformer:
    fps: 2
    path: "data/Indoor - Seattle Library"
    data_save_file: "/content/data/Indoor - train" #file path without .npz
    enable_benchmark_test: false
    test_path: "data/test/Mixed"
    test_save_file: "/content/data/Indoor - test" #file path without .npz
data:
    HEIGHT: 64
    WIDTH: 64
    CHANNELS: 1
    SEQUENCE_LENGTH: 10
    VAL_INTENT: ""
    BENCHMARK_TEST_INTENT: ""
trainer:
    patch_size: 4
    img_channel: 1
    img_width: 128
    filter_size: 5
    stride: 1
    layer_norm: 0
    visual: 0
    BATCH: 8
    max_lr: 0.01
    lr: 0.00005
    epochs: 25
    lambda: 0.001  #L2 regularization #changed from 1e-4
    num_classes: 3
    wandb: true
    model_save_path: "models/"
    model:
        name: "PredRNN"
        focal_loss_gamma: 1
        convlstm_hidden: 128
        num_conv_lstm_layers: 1
        conv_dropout: 0.2
        decouple_beta: 0.1
        pretrained_path: ""
        optimizer_path: ""
        scheduler_path: ""
        lr_after_load: ""

