global: 
    root_dir: ""
    iteration: "library_aditi_balanced_run2"
    enable_preprocessing: false
transformer:
    fps: 5
    path: "data/LibraryAditi"
    data_save_file: "data/processed/lib_aditi" #file path without .npz
    # resolution: [128,128] #can you change the code to use resolution values from data.HEIGHT and data.WIDTH?
data:
    HEIGHT: 128
    WIDTH: 128
    CHANNELS: 3
    SEQUENCE_LENGTH: 8
trainer:
    BATCH: 8
    lr: 0.01
    epochs: 20
    lambda: 0.001  #L2 regularization #changed from 1e-4
    num_classes: 3
    model_save_path: "../efs/Capstone/models/"
    model:
        name: "ConvLSTM"
        convlstm_hidden: 128
        num_conv_lstm_layers: 1
        pretrained_path: ""
        optimizer_path: ""
