global: 
    root_dir: ""
    iteration: "indoor_intent_new_test"
    description: "indoor_baseline full run INTENT CORRECTED"
    enable_preprocessing: False
    seed: 8
    enable_intent: True
    enable_wandb: False
transformer:
    fps: 2
    path: "data/"
    data_save_file: "data/train" #file path without .npz
    enable_benchmark_test: True
    test_path: "data/"
    test_save_file: "data/test" #file path without .npz
data:
    HEIGHT: 64
    WIDTH: 64
    CHANNELS: 1
    SEQUENCE_LENGTH: 10
    BENCHMARK_TEST_INTENT: ""
trainer:
    BATCH: 32
    lr: 0.0001
    epochs: 20
    lambda: 0.001  #L2 regularization #changed from 1e-4
    num_classes: 3
    model_save_path: "models/"
    model:
        name: "ConvLSTM"
        convlstm_hidden: "256"
        num_conv_lstm_layers: 1
        pretrained_path: ""
        optimizer_path: ""