global: 
    root_dir: ""
    iteration: "trans5mult0.7and1.2pick2"
    description: "intent_indoor_baseline full run changed run params"
    enable_preprocessing: false
    seed: 8
    enable_intent: true
    enable_wandb: true
transformer:
    fps: 2
    path: "data/Indoor - train"
    data_save_file: "data/processed/Indoor - train" #file path without .npz
    enable_benchmark_test: true
    test_path: "data/Indoor - test"
    test_save_file: "data/processed/Indoor - test" #file path without .npz
data:
    HEIGHT: 64
    WIDTH: 64
    CHANNELS: 1
    SEQUENCE_LENGTH: 10
    VAL_INTENT: ""
    BENCHMARK_TEST_INTENT: ""
trainer:
    BATCH: 8
    lr: 0.0001
    epochs: 25
    lambda: 0.01  #L2 regularization #changed from 1e-4
    num_classes: 3
    model_save_path: "models/"
    model:
        name: "ConvLSTM"
        convlstm_hidden: "256"
        num_conv_lstm_layers: 1
        pretrained_path: ""
        optimizer_path: ""
