global:
    root_dir: ""
    iteration: "intent_benchmark_indoor_test"
    enable_preprocessing: false
    seed: 8
    enable_intent: true
transformer:
    fps: 2
    path: "data/Indoor - Seattle Library"
    data_save_file: "/content/data/Indoor - train" #file path without .npz
    enable_benchmark_test: true
    test_path: "data/test/Mixed"
    test_save_file: "/content/data/Indoor - test" #file path without .npz
data:
    HEIGHT: 64
    WIDTH: 64
    CHANNELS: 1
    SEQUENCE_LENGTH: 10
    VAL_INTENT: ""
    BENCHMARK_TEST_INTENT: ""
trainer:
    patch_size: 4
    img_channel: 1
    img_width: 128
    filter_size: 5
    stride: 1
    layer_norm: 0
    visual: 0
    BATCH: 8
    max_lr: 0.01
    lr: 0.00005
    epochs: 50
    lambda: 0.001  #L2 regularization #changed from 1e-4
    num_classes: 3
    wandb: true
    model_save_path: "models/"
    model:
        name: "PredRNN"
        convlstm_hidden: 128
        num_conv_lstm_layers: 1
        decouple_beta: 0.1
        pretrained_path: "/content/drive/MyDrive/AI_Guide_Dog/models/debug/PredRNN_model_params_epoch_00000006_acc_67.80465747230387.pth"
        optimizer_path: "/content/drive/MyDrive/AI_Guide_Dog/models/debug/PredRNN_optimizer_params_epoch_00000006_acc_67.80465747230387.pth"
        scheduler_path: "/content/drive/MyDrive/AI_Guide_Dog/models/debug/PredRNN_scheduler_params_epoch_00000006_acc_67.80465747230387.pth"
