VID_PATH = "../../data/extracted_videos/"
VID_PATH_OG = "../../data/videos_new/"
LABEL_FILE = "../../data/data.npy"
PROCESSED_PATH = "../data_temp/processed/"
DATA_SAVE_PATH = "../data_temp/labeled_videos/"
MODELS_PATHS = "./models/"
# LABEL_PATH = '../../data/labels/'
FRAME_RATE = 2
BATCH = 128
SEQUENCE_LENGTH = 10
HEIGHT = 128
WIDTH = 128
CHANNELS = 3